// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DataDdsTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "DataDds.h"
#include "DataDdsTypeObject.h"
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerDataDdsTypes()
{
    TypeObjectFactory *factory = TypeObjectFactory::get_instance();
    factory->add_type_object("DataDDS", GetDataDDSIdentifier(true), GetDataDDSObject(true));
    factory->add_type_object("DataDDS", GetDataDDSIdentifier(false), GetDataDDSObject(false));

}

const TypeIdentifier* GetDataDDSIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("DataDDS", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetDataDDSObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("DataDDS", complete);
}

const TypeObject* GetDataDDSObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataDDS", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteDataDDSObject();
    }
    //else
    return GetMinimalDataDDSObject();
}

const TypeObject* GetMinimalDataDDSObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataDDS", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_size;
    mst_size.common().member_id(memberId++);
    mst_size.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_size.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_size.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_size.common().member_flags().IS_OPTIONAL(false);
    mst_size.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_size.common().member_flags().IS_KEY(false);
    mst_size.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_size.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 size_hash("size");
    for(int i = 0; i < 4; ++i)
    {
        mst_size.detail().name_hash()[i] = size_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_size);

    MinimalStructMember mst_size2;
    mst_size2.common().member_id(memberId++);
    mst_size2.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_size2.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_size2.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_size2.common().member_flags().IS_OPTIONAL(false);
    mst_size2.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_size2.common().member_flags().IS_KEY(false);
    mst_size2.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        mst_size2.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    MD5 size2_hash("size2");
    for(int i = 0; i < 4; ++i)
    {
        mst_size2.detail().name_hash()[i] = size2_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_size2);

    MinimalStructMember mst_vec_datai;
    mst_vec_datai.common().member_id(memberId++);
    mst_vec_datai.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_vec_datai.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_vec_datai.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_vec_datai.common().member_flags().IS_OPTIONAL(false);
    mst_vec_datai.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_vec_datai.common().member_flags().IS_KEY(false);
    mst_vec_datai.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_vec_datai.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("int32_t", 0, false));


    MD5 vec_datai_hash("vec_datai");
    for(int i = 0; i < 4; ++i)
    {
        mst_vec_datai.detail().name_hash()[i] = vec_datai_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_vec_datai);

    MinimalStructMember mst_vec_dataf;
    mst_vec_dataf.common().member_id(memberId++);
    mst_vec_dataf.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_vec_dataf.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_vec_dataf.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_vec_dataf.common().member_flags().IS_OPTIONAL(false);
    mst_vec_dataf.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_vec_dataf.common().member_flags().IS_KEY(false);
    mst_vec_dataf.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_vec_dataf.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("float", 0, false));


    MD5 vec_dataf_hash("vec_dataf");
    for(int i = 0; i < 4; ++i)
    {
        mst_vec_dataf.detail().name_hash()[i] = vec_dataf_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_vec_dataf);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataDDS", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataDDS", false);
}

const TypeObject* GetCompleteDataDDSObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("DataDDS", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_size;
    cst_size.common().member_id(memberId++);
    cst_size.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_size.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_size.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_size.common().member_flags().IS_OPTIONAL(false);
    cst_size.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_size.common().member_flags().IS_KEY(false);
    cst_size.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_size.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_size.detail().name("size");

    type_object->complete().struct_type().member_seq().emplace_back(cst_size);

    CompleteStructMember cst_size2;
    cst_size2.common().member_id(memberId++);
    cst_size2.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_size2.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_size2.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_size2.common().member_flags().IS_OPTIONAL(false);
    cst_size2.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_size2.common().member_flags().IS_KEY(false);
    cst_size2.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    {
        std::string cppType = "int32_t";
        if (cppType == "long double")
        {
            cppType = "longdouble";
        }
        cst_size2.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier(cppType, false));
    }

    cst_size2.detail().name("size2");

    type_object->complete().struct_type().member_seq().emplace_back(cst_size2);

    CompleteStructMember cst_vec_datai;
    cst_vec_datai.common().member_id(memberId++);
    cst_vec_datai.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_vec_datai.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_vec_datai.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_vec_datai.common().member_flags().IS_OPTIONAL(false);
    cst_vec_datai.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_vec_datai.common().member_flags().IS_KEY(false);
    cst_vec_datai.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_vec_datai.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("int32_t", 0, true));


    cst_vec_datai.detail().name("vec_datai");

    type_object->complete().struct_type().member_seq().emplace_back(cst_vec_datai);

    CompleteStructMember cst_vec_dataf;
    cst_vec_dataf.common().member_id(memberId++);
    cst_vec_dataf.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_vec_dataf.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_vec_dataf.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_vec_dataf.common().member_flags().IS_OPTIONAL(false);
    cst_vec_dataf.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_vec_dataf.common().member_flags().IS_KEY(false);
    cst_vec_dataf.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_vec_dataf.common().member_type_id(*TypeObjectFactory::get_instance()->get_sequence_identifier("float", 0, true));


    cst_vec_dataf.detail().name("vec_dataf");

    type_object->complete().struct_type().member_seq().emplace_back(cst_vec_dataf);


    // Header
    type_object->complete().struct_type().header().detail().type_name("DataDDS");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("DataDDS", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("DataDDS", true);
}
