// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DdsDataPubSubTypes.h
 * This header file contains the declaration of the serialization functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _DDSDATA_PUBSUBTYPES_H_
#define _DDSDATA_PUBSUBTYPES_H_

#include <fastdds/dds/topic/TopicDataType.hpp>
#include <fastrtps/utils/md5.h>

#include "DdsData.h"

#if !defined(GEN_API_VER) || (GEN_API_VER != 1)
#error Generated DdsData is not compatible with current installed Fast DDS. Please, regenerate it with fastddsgen.
#endif  // GEN_API_VER

 /*!
  * @brief This class represents the TopicDataType of the type DdsData defined by the user in the IDL file.
  * @ingroup DDSDATA
  */
class DdsDataPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsData type;

    eProsima_user_DllExport DdsDataPubSubType();

    eProsima_user_DllExport virtual ~DdsDataPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        new (memory) DdsData();
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the TopicDataType of the type DdsAlarm defined by the user in the IDL file.
 * @ingroup DDSDATA
 */
class DdsAlarmPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsAlarm type;

    eProsima_user_DllExport DdsAlarmPubSubType();

    eProsima_user_DllExport virtual ~DdsAlarmPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        new (memory) DdsAlarm();
        return true;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the TopicDataType of the type DdsStatus defined by the user in the IDL file.
 * @ingroup DDSDATA
 */
class DdsStatusPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsStatus type;

    eProsima_user_DllExport DdsStatusPubSubType();

    eProsima_user_DllExport virtual ~DdsStatusPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        (void)memory;
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the TopicDataType of the type DdsConfig defined by the user in the IDL file.
 * @ingroup DDSDATA
 */
class DdsConfigPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsConfig type;

    eProsima_user_DllExport DdsConfigPubSubType();

    eProsima_user_DllExport virtual ~DdsConfigPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        (void)memory;
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the TopicDataType of the type DdsDataCollection defined by the user in the IDL file.
 * @ingroup DDSDATA
 */
class DdsDataCollectionPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsDataCollection type;

    eProsima_user_DllExport DdsDataCollectionPubSubType();

    eProsima_user_DllExport virtual ~DdsDataCollectionPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        (void)memory;
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};
/*!
 * @brief This class represents the TopicDataType of the type DdsAlarmCollection defined by the user in the IDL file.
 * @ingroup DDSDATA
 */
class DdsAlarmCollectionPubSubType : public eprosima::fastdds::dds::TopicDataType
{
public:

    typedef DdsAlarmCollection type;

    eProsima_user_DllExport DdsAlarmCollectionPubSubType();

    eProsima_user_DllExport virtual ~DdsAlarmCollectionPubSubType();

    eProsima_user_DllExport virtual bool serialize(
        void* data,
        eprosima::fastrtps::rtps::SerializedPayload_t* payload) override;

    eProsima_user_DllExport virtual bool deserialize(
        eprosima::fastrtps::rtps::SerializedPayload_t* payload,
        void* data) override;

    eProsima_user_DllExport virtual std::function<uint32_t()> getSerializedSizeProvider(
        void* data) override;

    eProsima_user_DllExport virtual bool getKey(
        void* data,
        eprosima::fastrtps::rtps::InstanceHandle_t* ihandle,
        bool force_md5 = false) override;

    eProsima_user_DllExport virtual void* createData() override;

    eProsima_user_DllExport virtual void deleteData(
        void* data) override;

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED
    eProsima_user_DllExport inline bool is_bounded() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_BOUNDED

#ifdef TOPIC_DATA_TYPE_API_HAS_IS_PLAIN
    eProsima_user_DllExport inline bool is_plain() const override
    {
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_IS_PLAIN

#ifdef TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE
    eProsima_user_DllExport inline bool construct_sample(
        void* memory) const override
    {
        (void)memory;
        return false;
    }

#endif  // TOPIC_DATA_TYPE_API_HAS_CONSTRUCT_SAMPLE

    MD5 m_md5;
    unsigned char* m_keyBuffer;
};

#endif // _DDSDATA_PUBSUBTYPES_H_